[package]
name = "cosmic-applet-ip"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "A COSMIC panel applet that displays the current IP address of the computer"
repository = "https://github.com/cpknight/cosmic-applet-ip"

[[bin]]
name = "cosmic-applet-ip"
path = "src/main.rs"

[dependencies]
futures-util = "0.3"
if-addrs = "0.13"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.i18n-embed]
version = "0.16"
features = ["fluent-system", "desktop-requester"]

[dependencies.i18n-embed-fl]
version = "0.10"

[dependencies.rust-embed]
version = "8"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = [
    "applet",
    "applet-token",
    "dbus-config",
    "multi-window",
    "tokio",
    "wayland",
    "winit",
]

[profile.release]
opt-level = 3
lto = "thin"
panic = "abort"
